### ISSUE TITLE
Selenium version? Unable to save animation

### ISSUE THREAD

**Issue by manolotis** [NVlabs/trajdata#38]
Hi, 

I installed trajdata and I am able to run most examples. When running `visualization_example.py`, I get a very nice Bokeh animation of the scene. I would like to save a .mp4 or .avi of that animation with the "Render video" option, but it throws an error because I do not have selenium installed. I installed selenium (simply `pip install selenium`), and now that module is found, but there is a version mismatch. With the latest version (4.18.1), I get the following error:

```
Exception in thread Thread-5 (execute_save_animation):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "[...]/venv/lib/python3.10/site-packages/trajdata/visualization/interactive_animation.py", line 457, in execute_save_animation
    driver = webdriver.Chrome(chrome_options=chrome_options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'chrome_options'
```
Googling a bit, it turns out that argument `chrome_options` is no longer there in newer versions, so I tried going back to one which had it (4.5.0), but that one has some other required parameters that I am unsure what they should be...

So just to be able to save this nice animation, which version of selenium do you have installed? Can this be added to the requirements such that it's automatically installed with trajdata? 

Thank you!

**Comment by Daboolu** [comment]
I resolved the issue by installing the following packages in this specific order:

`pip install selenium==4.4.0 `
`pip install matplotlib==3.6.0 `
`pip install numpu==1.24`

After installing these versions, please try running your project or script again. If you continue to experience any problems, feel free to let me know here. Hope this helps!
